
FROM php:8.3-apache

ENV APACHE_DOCUMENT_ROOT=/var/www/html/public \
  COMPOSER_ALLOW_SUPERUSER=1

RUN apt-get update && apt-get install -y --no-install-recommends \
  git curl unzip zip \
  libzip-dev libpng-dev libjpeg62-turbo-dev libfreetype6-dev \
  libonig-dev libxml2-dev libicu-dev libssl-dev \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip intl opcache \
 && a2enmod rewrite headers \
 && sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf /etc/apache2/apache2.conf \
 && printf "ServerName localhost\n" > /etc/apache2/conf-available/servername.conf && a2enconf servername \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock* ./
RUN composer install --prefer-dist --no-interaction --no-progress

COPY . .

RUN chown -R www-data:www-data storage bootstrap/cache && \
  find storage -type d -exec chmod 775 {} \; && chmod -R 775 bootstrap/cache

EXPOSE 80
CMD ["apache2-foreground"]
